services:
  gateway:
    build: ./gateway-service
    container_name: gateway
    ports:
      - "5005:5005"
    depends_on:
      - tts
      - stt

  tts:
    build: ./tts-service
    container_name: tts
    ports:
      - "5006:5006"
    volumes:
      - /var/apps/opt/ai-stack/model/f5tts:/model

  stt:
    build: ./stt-service
    container_name: stt
    ports:
      - "5007:5007"
