services:
  gateway:
    build: ./gateway-service
    container_name: gateway
    ports:
      - "5005:5000"
    depends_on:
      - tts
      - stt

  tts:
    build: ./tts-service
    container_name: tts
    ports:
      - "5001:5000"

  stt:
    build: ./stt-service
    container_name: stt
    ports:
      - "5002:5000"
